project:
  language: ar
  exp_name: DTrOCR_500m_1ep

  generation:
    num_beams: 4

  dataset:
    bucket_name: ocr88
    folder: generated_images/
    language: ar 
    num_workers: 2
    prefetch_factor: 300
    batch_size: 176
    force_reload: False
    cache_file: cache/file_list_2m.pkl

    split:
      train: 0.99
      test: 0.009
      val: 0.001


  train:
    num_epochs: 1
    learning_rate: 1e-4
    save_every_n_batches: 10000
    validate_every_n_batches: 10
    print_every_n_batches: 10
    evaluation_metric: cer
    use_amp: True

