project:
  language: ar
  exp_name: DTrOCR_ar_500m

  dataset:
    bucket_name: ocr88
    folder: generated_images/
    language: ar 
    num_workers: 4
    prefetch_factor: 20
    batch_size: 32
    force_reload: False
    cache_file: cache/file_list_5m.pkl

    split:
      train: 0.99
      test: 0.009
      val: 0.001


  train:
    num_epochs: 1
    learning_rate: 1e-4
    save_every_n_batches: 10000
    validate_every_n_batches: 1000
    print_every_n_batches: 100

